---
- name: check network manager services
  hosts: all
  become: yes
  tasks:
  - name: Start netwrork service , if not running
    service:
      name: NetworkManager
      state: started
      enabled: yes
